# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
maven_group=me.caseload
archives_base_name=knockbacksync

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.154.2+26.2

githubRepo=CASELOAD7000/knockback-sync
